### ISSUE TITLE
Asks for tracking ID even though I provided it.

### ISSUE THREAD

**Issue by vincentleeuwen** [fknussel/react-router-ga#1]
Quite basic usage fails.

<Analytics id="UA-XXXXXXXXX-1">

Give me:

[react-router-ga] Tracking ID is required.

**Comment by fknussel** [comment]
Hey Vincent, thanks for reporting this :)

I'm currently using this on production and it's working just fine.

Could you please post a link to your project (if public) or create an example to replicate your current setup so that I can further look into this?

Thanks!

**Comment by vincentleeuwen** [comment]
The project is not public unfortunately, the setup was something like:

```
<Router>
  <Analytics id={process.env.GA_ID}>
    <Route>
    ...
    </Route>
  </Analytics>
</Router>
```

**Comment by fknussel** [comment]
Hi Vincent. Can you please try hardcoding the Analytics ID to see if it
works that way? My hunch is the environment variable is not being picked
up. Did you try to debug the value of ‘process’ to make sure your GA_ID
variable was indeed being injected?

**Comment by fknussel** [comment]
Hi Vicent, did you manage to make this work?
