### ISSUE TITLE
Sends a duplicate pageview on initial page load

### ISSUE THREAD

**Issue by samatcd** [fknussel/react-router-ga#12]
This issue causes an artificially low bounce rate in Google Analytics.

This is triggered because the `initialize` method in the  constructor calls `window.ga('send', 'pageview')`, then on `componentDidMount` the `sendPageView` method is called, which sends another pageview.

This is also the case even when using `trackPathnameOnly` option, since the `lastPathname` property isn't initialized in the constructor.

My solution was to remove the `window.ga('send', 'pageview')` command from the `initialize` method and instead rely on the call in the `sendPageView` method.

**Comment by fknussel** [comment]
Hey @samatcd thanks heaps for reporting this and posting your solution!

Just ran some tests and you are correct. I've released `react-router-ga@1.2.2` which fixes this.

Cheers :)
