### ISSUE TITLE
An issue with testing around React-Router-UA

### ISSUE THREAD

**Issue by tosbourn** [fknussel/react-router-ga#3]
This is a great tool, thanks!

I've spotted an issue whilst testing.

Any test that hits Routes now fails with 

```
TypeError: Cannot read property 'parentNode' of undefined
```

Some digging let me to this (unminified) code

```
// Load Google Analytics
        (function(i, s, o, g, r, a, m) {
          i["GoogleAnalyticsObject"] = r;
          (i[r] =
            i[r] ||
            function() {
              (i[r].q = i[r].q || []).push(arguments);
            }),
            (i[r].l = 1 * new Date());
          (a = s.createElement(o)), (m = s.getElementsByTagName(o)[0]);
          a.async = 1;
          a.src = g;
          m.parentNode.insertBefore(a, m);
        })(
          window,
          document,
          "script",
          "https://www.google-analytics.com/analytics.js",
          "ga"
        );
```

`m.parentNode.insertBefore(a, m);` is failing because `s.getElementsByTagName(o)[0]` is returning undefined. I presume because there are no `<script>` tags set at this point in the execution of the tests.

Is there something I need to call before my tests or is there something I need to do differently in order for this to silently fail (I don't care for analytics in tests).

**Comment by tosbourn** [comment]
The "fix" for me was to add this to my test file.

``` javascript
jest.mock("react-router-ga", () => "stub");
```

**Comment by fknussel** [comment]
Thanks for posting the solution to your problem @tosbourn 🙂 

Closing this now as it's resolved.
